#!/bin/bash

ssh_opts=(
    -o BatchMode=yes
    -o CheckHostIP=no
    -o StrictHostKeyChecking=no
    -o HashKnownHosts=no
    -o ConnectTimeout=16
)

if [[ $1 == *"@"* ]]
  then
    SERVER=$( echo ${1##*@} )
  else
    SERVER=${1}
fi

SSH_VERSION=$(ssh -vN "${ssh_opts[@]}" "$@" -l ForceLogin2Fail 2>&1 | grep "remote software version")
echo ${SSH_VERSION#debug1: }
