#!/usr/bin/env bash

#  +---------------------------------------------------------------------------------------------------+
#  | Title        : ssh-hostkey                                                                        |
#  |                                                                                                   |
#  | Description  : prints server host keys in several formats                                         |
#  |                                                                                                   |
#  | Author       : Sven Wick <sven.wick@gmx.de>                                                       |
#  | Contributors : Geert Stappers <https://github.com/stappersg>                                      |
#  | URL          : https://github.com/vaporup/ssh-tools                                               |
#  |                                                                                                   |
#  | Based On     : https://unix.stackexchange.com/questions/126908/get-ssh-server-key-fingerprint     |
#  +---------------------------------------------------------------------------------------------------+

remote_host=$1

the_hostkeys=$( mktemp /tmp/ssh-hostkeys.XXXXXX )
trap "rm -f $the_hostkeys" EXIT

ssh-keyscan $remote_host > $the_hostkeys 2>/dev/null

fingerprint_hashes=( md5 sha256 )

function get_fingerprints () {

  hash_type=$1

  ssh-keygen -E $hash_type -qlf $the_hostkeys | while IFS= read -r line; do

    key_data=( $(printf '%s\n' "$line") )
    key_size=${key_data[0]}
    key_hash=${key_data[1]}
    key_remote_host=${key_data[2]}
    key_type=${key_data[3]}
    key_hash_type="${key_hash%%:*}"
    key_hash_data="${key_hash#*:}"

    printf "%10s%6s%8s %s\n" $key_type $key_size $key_hash_type $key_hash_data

  done

}

for fingerprint_hash in ${fingerprint_hashes[@]}; do

  get_fingerprints $fingerprint_hash

done | sort
