#!/usr/bin/env bash

#  +----------------------------------------------------------------------+
#  | Title        : ssh-version                                           |
#  |                                                                      |
#  | Description  : Shows version of the SSH server you are connecting to |
#  |                                                                      |
#  | Author       : Sven Wick                                             |
#  | Email        : sven.wick@gmx.de                                      |
#  | URL          : https://github.com/vaporup/ssh-tools                  |
#  +----------------------------------------------------------------------+

ssh_opts=(
    -o BatchMode=yes
    -o CheckHostIP=no
    -o StrictHostKeyChecking=no
    -o HashKnownHosts=no
    -o ConnectTimeout=16
    -o PasswordAuthentication=no
    -o PubkeyAuthentication=no
)

if [[ $1 == *"@"* ]]
  then
    SERVER=$( echo ${1##*@} )
  else
    SERVER=${1}
fi

SSH_VERSION=$(ssh -vN "${ssh_opts[@]}" "$@" -l ForceLogin2Fail 2>&1 | grep "remote software version")
echo ${SSH_VERSION#debug1: }
