#!/usr/bin/env bash
#
# Default SSH Options
#

SSH_OPTS=(
    -o BatchMode=yes
    -o CheckHostIP=no
    -o StrictHostKeyChecking=no
    -o HashKnownHosts=no
    -o ConnectTimeout=3
)

counter=1

echo "SSHTRACEROUTE to ${1}"

while read line; do

  printf "%2i  %s\n" "$counter" "$line"
  ((counter++))

done < <(ssh -v "${SSH_OPTS[@]}" ForceLogin2Fail@$1 2>&1 \
         | awk '/Authenticating to/ { print $4 }
                /Executing proxy command/ { print }
                /^ssh:/             { print $0 }')
